# Generated by Django 4.0.4 on 2022-05-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_upload'),
        ),
    ]
