# Generated by Django 4.0.4 on 2022-05-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapp', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
