# Generated by Django 4.0.4 on 2022-05-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastyapp', '0004_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='location',
            new_name='post',
        ),
    ]
